[project]
name = "moderngl_playground"
version = "0.1.0"
description = "A playground project for python moderngl library"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "moderngl-window>=3.0.3",
    "moderngl>=5.12.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
start = "moderngl_playground.__main__:main"
